### ISSUE TITLE
❌ Incompatible with ESPHome 2025.7.0: setup_entity import fails

### ISSUE THREAD

**Issue by HerrBausW** [mampfes/esphome_obis_d0#24]
Hi 👋

Since updating to ESPHome `2025.7.0`, the build fails with the following error:

```
ERROR Unable to import component obis_d0:
ImportError: cannot import name 'setup_entity' from 'esphome.cpp_helpers'
```
**Full traceback:**

`ImportError: cannot import name 'setup_entity' from 'esphome.cpp_helpers' (/esphome/esphome/cpp_helpers.py)`
This seems to come from the line in `__init__.py`:

`from esphome.cpp_helpers import setup_entity`
However, `setup_entity` was removed in ESPHome 2025.7.0, which causes the build to break.

**To reproduce:**

```
external_components:
  - source: github://mampfes/esphome_obis_d0

obis_d0:
  id: my_sm
  uart_id: my_uart
```
Could you please update the component to be compatible with 2025.7.0 and newer?

Let me know if you need help testing.
Thanks a lot for your great work! 🙏

Best regards,
Enrico

**Comment by HerrBausW** [comment]
✅ I've submitted a pull request to fix this:
https://github.com/mampfes/esphome_obis_d0/pull/25

It removes the deprecated TEXT_SENSOR_SCHEMA and fixes the removed setup_entity import for ESPHome 2025.7.0.

Tested and working with ESPHome 2025.7.0.

Thanks again for this useful component! 🙌
